// Mapping of friendly track names to internal types or configs.
// For now, ambient tracks are generated by the AudioEngine; binaural tracks use presets.
import { FrequencyPresets } from './audioEngine';

export type TrackKey = 'Rain' | 'Whistle' | 'Deep Focus' | 'Ocean' | 'White Noise' | 'Alpha' | 'Beta' | 'Gamma' | 'Theta' | 'Delta';

export const AudioAssets: Record<TrackKey, any> = {
  'Rain': { type: 'ambient', ambientType: 'rain' },
  'Whistle': { type: 'binaural', preset: FrequencyPresets.ALPHA },
  'Deep Focus': { type: 'binaural', preset: FrequencyPresets.BETA },
  'Ocean': { type: 'ambient', ambientType: 'ocean' },
  'White Noise': { type: 'ambient', ambientType: 'whitenoise' },
  'Alpha': { type: 'binaural', preset: FrequencyPresets.ALPHA },
  'Beta': { type: 'binaural', preset: FrequencyPresets.BETA },
  'Gamma': { type: 'binaural', preset: FrequencyPresets.GAMMA },
  'Theta': { type: 'binaural', preset: FrequencyPresets.THETA },
  'Delta': { type: 'binaural', preset: FrequencyPresets.DELTA },
};

export default AudioAssets;
